### PR TITLE
chore: improve ide-extension testing

### PR DESCRIPTION
**Pull request by openscript**

### CODE REVIEW

**Comment by felixhaeberle** [comment]
@openscript if I should take over this task, please notify me — or if you are stuck / if there are any problems in setting this up. 

the changes in here potentially have to be copied out of this PR because I saw there is a mismatch between main & this PR so probably start with a fresh PR. 

we also switched to pnpm, maybe that also further resolved issues here.

**Comment by openscript** [comment]
I waited for the pnpm migration and will continue with it after sleeping later today.

**Comment by openscript** [comment]
> if there are any problems in setting this up

@felixhaeberle I'm hoping the migration to PNPM fixes the problems.

**Comment by openscript** [comment]
Continue with smaller PRs.

**Pull request closed without merging**
