### PR TITLE
Extended and updated SvelteKit Guide.

### PR DESCRIPTION
**Pull request by AdamTmHun**
This PR extends the [SvelteKit guide on the website](https://inlang.com/g/2fg8ng94/guide-nilsjacobsen-buildAGlobalSvelteApp). Does not update the example.

It also fixes a typo in it's marketplace-manifest.json.

### CODE REVIEW

**Comment by AdamTmHun** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by AdamTmHun** [comment]
recheck

**Comment by LorisSigrist** [comment]
Thank you for writing this! This is going to help new users a lot when getting started.

There is some odd display behaviour on the Console output section. Could you fix that?
Screenshot 2023-11-26 at 17 51 06

**Comment by AdamTmHun** [comment]
@LorisSigrist Hopefully it is fixed now. Can you clarify?

**Comment by LorisSigrist** [comment]
Formatting is good now. 
Could you rename `redirectHref` to `translatePath` ? 
`redirectHref implies that it also works with external links. `translatePath` is the same name astro uses for it's i18n routing, so there will hopefully be some more familiarity.

**Comment by AdamTmHun** [comment]
@LorisSigrist I renamed it.

**Comment by LorisSigrist** [comment]
Thank you! I'll merge this tomorrow morning.

**Pull request merged**
