### PR TITLE
fix link syntax

### PR DESCRIPTION
**Pull request by KTibow**

### CODE REVIEW

**Comment by KTibow** [comment]
> a Pull Request Comment

why is this a proper noun? is this supposed to be a review comment or just a normal comment?

**Comment by AdamTmHun** [comment]
@KTibow just a regular comment. Take a look at how I did it #1745

**Comment by KTibow** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by AdamTmHun** [comment]
now comment "recheck"

**Comment by samuelstroschein** [comment]
Thanks @KTibow !

**Pull request merged**
