### PR TITLE
Update translations - Add FR & fix EN

### PR DESCRIPTION
**Pull request by WarningImHack3r**
Add the entire French localization, and fix some typos in English.

Side note: why do you localize social network names? Aren't they global and immutable?

Preview the messages on https://inlang.com/github.com/WarningImHack3r/monorepo.

### CODE REVIEW

**Comment by samuelstroschein** [comment]
hi @WarningImHack3r, 

THANKS!

1. please sign the CLA by commenting with "I have read the CLA Document and I hereby sign the CLA"
2. how was the experience? cc @NiklasBuchfink who will be interested in your feedback

**Comment by WarningImHack3r** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by samuelstroschein — APPROVED** [review]

**Comment by samuelstroschein** [comment]
> Side note: why do you localize social network names? Aren't they global and immutable?

Likely a mistake. Thanks for the nudge!

**Comment by WarningImHack3r** [comment]
> THANKS!

No problem @samuelstroschein! Quick and easy :)

> 2. how was the experience? cc @NiklasBuchfink who will be interested in your feedback

The web editor is very well-made! ↹-compatible, fast auto-translate, nice working UI, all good! The only issue is #1614 but it's not much and a bit of an edge case :)

About your repo:
- I talked about the useless translations for brands/social networks but you just replied about it
- There is **a lot** of missing translations/hardcoded strings (+ typos) in your code
- Some strings are duplicates, they are in different places on the website but I don't think it's useful—including the split strings you can easily join to avoid having to translate twice

**Comment by samuelstroschein** [comment]
> I talked about the useless translations for brands/social networks but you just replied about it

I was about to fix them but couldn't find them. See https://inlang.com/editor/github.com/inlang/monorepo?id=footer_resources_github, https://inlang.com/editor/github.com/inlang/monorepo?id=footer_resources_discord, and https://inlang.com/editor/github.com/inlang/monorepo?id=footer_resources_twitter. All seem un-translated. Which social networks have been translated?

> There is a lot of missing translations/hardcoded strings (+ typos) in your code

Yes. We are incrementally extracting hard-coded strings. 

> Some strings are duplicates, they are in different places on the website but I don't think it's useful

Yes, complete chaos. The chaos will become tidy over time.

**Pull request merged**
