### PR TITLE
Fix #1639

### LINKED ISSUE #1639: [bug] "Extract message" function makes message ID lowercase and removes `_`
### Problem

"Extract message" function makes message ID lowercase and removes `_`

### Expected behavior

To preserve the `_` and message ID case. Probably replace the `.` with `_`

### Reproduction

1. Select a text to convert into a message
2. Provide the message ID that contains uppercase letters and/or `_`
3. Insert the replacement `m`-message

### Other information

https://github.com/inlang/monorepo/assets/25585136/ecbb9e93-cdbf-43e2-9c03-ae01025bac3c

### PR DESCRIPTION
**Pull request by DanikVitek**
- Remove `.toLowercase()` call
- Don't remove `_`
- Replace `.` with `_`
- Improve readability

/claim #1639

### CODE REVIEW

**Comment by DanikVitek** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by felixhaeberle** [comment]
@DanikVitek The overall goal is to create snake case function names with id's which are valid js functions, as we need them for generating the paraglide functions. 

Can you outsource this transform function in a new file and add a test for various inputs?

**Comment by DanikVitek** [comment]
> Can you outsource this transform function in a new file?
@felixhaeberle Inside the `m-function-matcher` plugin or somewhere else?

**Comment by felixhaeberle** [comment]
@DanikVitek Looks great, thank you! Will merge it tomorrow.

**Comment by felixhaeberle** [comment]
@DanikVitek Thank you! 🙏

**Pull request merged**
