### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by KraXen72**
Describe the changes you have conducted here

Preview the messages on https://inlang.com/github.com/KraXen72/monorepo .

### CODE REVIEW

**Comment by felixhaeberle** [comment]
@KraXen72 You have to sign the CLA with posting: "I have read the CLA Document and I hereby sign the CLA" as a comment.

**Comment by KraXen72** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by KraXen72** [comment]
recheck

**Comment by KraXen72** [comment]
@felixhaeberle please take a look

**Comment by felixhaeberle** [comment]
@KraXen72 thanks!! 🤝

**Pull request merged**
