### PR TITLE
deprecate `detectedLanguageTags()` in `Plugin`

### PR DESCRIPTION
**Pull request by felixhaeberle**
This PR aims to deprecate `detectedLanguageTags`.

### CODE REVIEW

**Review by NilsJacobsen — APPROVED** [review]
Looks good to me 👍

**Comment by NiklasBuchfink** [comment]
@felixhaeberle Should I add the `sourceLanguageFilePath` to plugin-i18next in this PR too? (#1381)

**Comment by felixhaeberle** [comment]
@NiklasBuchfink I this PR feels applicable to you, go ahead 👍 Then, you don't need to release it again.

**Comment by felixhaeberle** [comment]
@NiklasBuchfink @NilsJacobsen have all manual test been successfully conducted?

**Comment by NiklasBuchfink** [comment]
@felixhaeberle Not yet, I currently have a problem with my local environment. I will test it right after this is fixed

**Comment by felixhaeberle** [comment]
@NiklasBuchfink You can merge & release after a successful test.

**Comment by NiklasBuchfink** [comment]
Everything works performantly in the editor with a repo with large language configuration. The changes have also solved the linting reactivity issues of the "Revert" and "Select and Delete".

Good work @felixhaeberle @NilsJacobsen 👍

**Pull request merged**
