### PR TITLE
fix: [bug] VSCode extension : "command "inlang.extractMessage" not found"

### LINKED ISSUE #1805: [bug] VSCode extension : "command "inlang.extractMessage" not found"
### Problem

After installing the official latest Inlang extension (inlang.vs-code-extension v1.21.0) on a fresh inlang Sveltekit project :

https://github.com/MarArMar/SvelteInlang

If running command from command pallette I have the error modal : 

Command "inlang: Extract Message"
resulted in an error
command "inlang.extractMessage" not found

Other commands fail as well

VSCode extension status page : 
Activation Event:Startup
Activation Time:118ms

If I uninstall all other extentions, uninstall Inlang, install inlang again, reload VSCode, even closing all VSCodes & reopening a fresh one, I get : 
Activation Event:onStartupFinished
Activation Time:72ms

And still the same error on commands

### Expected behavior

Commands work

### Reproduction

1. Clone https://github.com/MarArMar/SvelteInlang
2. pnpm install, pnpm dev to check if it works
3. Install inlang extension
4. Try to run the command "inlang: Extract Message"

### Other information

Windows 10
VSCode version 1.84.2 

Maybe something I thought of :

I see this activation event : 

workspaceContains:**/project.inlang.json

But I had a readme saying "project.inlang.json" shouldn't be used so I changed

Anyway I tried both with project.inlang.json & project.inlang/settings.json and both didn't work for me

- If I disable, re enable the VSCode extension, I see the message in the bottom bar : "inlang's extension activated" but still the same error
- I do not see any context tooltips if I hover over paraglide messages in my code

- I do see the documentation of params, like :

```
const greeting: (params: {
    name: {};
}, options?: {
    languageTag?: "en" | "de" | undefined;
}) => string
This message has been compiled by [inlang paraglide]

Don't edit the message's code. Use the [inlang ide extension], the [web editor] instead, or edit the translation files manually.

The params are NonNullable because the inlang SDK does not provide information on the type of a param (yet).
```

### PR DESCRIPTION
**Pull request by rishi-raj-jain**
fix #1805
/claim #1805

### CODE REVIEW

**Comment by rishi-raj-jain** [comment]
@felixhaeberle

The PR passes all the tests, yay!

Can we get it released under some pre version so that @MarArMar @SebbeBroman can test and confirm the fix?

**Comment by felixhaeberle** [comment]
@rishi-raj-jain Thanks! Did you test it on Windows with the repository provided by @MarArMar in the issue? 

cc @samuelstroschein Please do NOT hardcode any OS specific paths anymore like this. Never ever again 😄

**Comment by rishi-raj-jain** [comment]
@felixhaeberle 

> Did you test it on Windows with the repository provided by @MarArMar in the issue?

That's why I asked for a pre-release under some version so that I can install the extension in VS Code with my changes. Or is there a way I'm missing to test this?

**Comment by felixhaeberle** [comment]
@rishi-raj-jain Did you run `pnpm run dev` and then started the VS Code extension locally (in the debug window of VS Code) on Windows with this example https://github.com/MarArMar/SvelteInlang and it works? Then it can be merged I guess. Will double check it on my side too for MacOS.

**Comment by openscript** [comment]
@felixhaeberle I totally agree. Can we merge https://github.com/inlang/monorepo/pull/1795? How many more hours am I allowed to invest enhancing the results #1795? I've some more ideas after talking with Christian from wdio-vscode-service, but it's hard to give precise estimates. The 8 hours from #1428 used all up (and actually I've invested 15 hours on top, but it I put it as learning time into the books).

**Comment by felixhaeberle** [comment]
@rishi-raj-jain Can you add a changeset with `npx changeset` detailing your changes?

**Comment by rishi-raj-jain** [comment]
@felixhaeberle 

Done

**Comment by felixhaeberle** [comment]
@rishi-raj-jain Can you check why the CI isn't green anymore? Was fine at first.

**Comment by rishi-raj-jain** [comment]
@felixhaeberle 

I think someone updated the tests script to use the doppler without token

Screenshot 2023-12-12 at 5 16 29 PM

P.S. Nothing to do with my push

**Comment by felixhaeberle** [comment]
> Or is there a way I'm missing to test this?

@rishi-raj-jain To test it on Windows, you simply have to run the extensions dev process (pnpm run dev) on a Windows system & then verify https://github.com/MarArMar/SvelteInlang is working. Do you have the ability to test it on Windows by yourself?

**Comment by felixhaeberle** [comment]
@MarArMar @FredBuild @SebbeBroman Can anyone of you checkout this PR and test if this works on your machine?

**Comment by rishi-raj-jain** [comment]
@MarArMar @FredBuild @SebbeBroman Can anyone of you checkout this PR and test if this works on your machine? I'm searching for my Windows laptop right now!

**Comment by rishi-raj-jain** [comment]
[video.webm](https://github.com/inlang/monorepo/assets/46300090/854bdeaf-2361-42be-89ab-03ba54a3e105)

**Comment by rishi-raj-jain** [comment]
@felixhaeberle 

- I show the changes in the vs code extension at the timestamp of 13-20 seconds (which is what I've PR'd)

- at the end we get to see that the project compiles fine and upon hover the ide works as expected

**Comment by felixhaeberle** [comment]
@rishi-raj-jain The correct output should be something like:

Bildschirmfoto 2023-12-14 um 15 32 22

which isn't appearing in your case.

**Comment by felixhaeberle** [comment]
No, just hovering in a file with m functions. This is the standard behavior when having the extension installed.

**Review by felixhaeberle — CHANGES_REQUESTED** [review]
I think these changes are unrelated to the bug we experiencing which the ide extension not loading at all, as described in https://github.com/inlang/monorepo/pull/1869#issuecomment-1855990798

**Comment by felixhaeberle** [comment]
closing this in favor of https://github.com/inlang/monorepo/pull/1926

**Pull request closed without merging**
