### PR TITLE
improve tailwind css with RTL compatible classes

### PR DESCRIPTION
**Pull request by felixhaeberle**
@inlang/team this PR aims to improve our current usage of tailwind css classes ("left" and "right") and replaces them with the "start" & "end" logical counterparts (called logical properties).

This change allows RTL users to have our UI displayed correctly & is no further maintenance burden for us. Please use whenever possible the correct "start" & "end" alternatives & ulimately ban "right" & "left" from your CSS box model thinking.

Thanksyy <3

More on logical properties & why we should use them: 
https://www.bram.us/2019/09/19/css-logical-properties-and-values-the-next-step-of-css-evolution/

### CODE REVIEW

**Comment by NiklasBuchfink** [comment]
@felixhaeberle I have two thoughts:

1. Does it help to read the English RTL as we haven't translated or extract the messages for our apps in any RTL language yet? I asked my flatmate from Israel what he would expect.

2. The best use case at the moment would be to display and write the patterns of RTL languages from right to left. But we would need to parse them and we get the same problems as we have with the detection of a correct language tag.

**Comment by felixhaeberle** [comment]
@NiklasBuchfink I don't understand both of your points, can you elaborate?

1. English is never RTL. Why would somebody display English in RTL?
2. The text display is the same, just flipped.

This PR is only about replacing the legacy CSS classes with more modern ones which align with the goal of our app to be served in multiple languages in the future.

**Comment by NilsJacobsen** [comment]
I feel like the maintenance burden is too significant for basically no user asking for this. I quickly checked other big companies with many employees to see if they support it. The answer is yes, but they have a lot of layout problems. If they can't maintain it, we shouldn't try to accomplish it with a handful of people.

image
image
image

**Comment by felixhaeberle** [comment]
What is holding us back from just using the modern CSS tailwind alternatives to the standard ones? 

We already decided not to go "full RTL support" but to make our components more RTL friendly ootb with using modern CSS alternative. 

I don't see a maintenance burden in using a modern CSS standard which is interchangeable to the current one, but with great benefits.

**Comment by samuelstroschein** [comment]
> I don't see a maintenance burden in using a modern CSS standard which is interchangeable to the current one, but with great benefits. 

Because you need to a) disallow `m{l,t,r,b}`, `p{l,t,r,b}` and b) explain developers that a) can't be used anymore

a) is a one time effort
b) is a continuous effort

a and b combined don't achieve c, your stated goal of RTL support.

**Comment by felixhaeberle** [comment]
Gotcha. Still not changing my mind on it but if team agrees on not going for it, we skip it for now. 👍

**Pull request closed without merging**
