### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by misa1515**
Describe the changes you have conducted here

Preview the messages on https://inlang.com/github.com/misa1515/monorepo .

### CODE REVIEW

**Comment by felixhaeberle** [comment]
@misa1515 thanks for your contribution! Can you add the missing ones here?
-> https://inlang.com/editor/github.com/inlang/monorepo?lang=en&lang=sk

**Comment by felixhaeberle** [comment]
@flornkm merge?

**Comment by flornkm** [comment]
@felixhaeberle I haven't had time to resolve the merge conflicts yet, will do that later today.

**Comment by flornkm** [comment]
@felixhaeberle I haven't had time to resolve the merge conflicts yet, will do that later today.

**Comment by flornkm** [comment]
@felixhaeberle it doesn't seem to work for me as someone else had already added `sk` language on the main branch. Can you double check? I've merged main into this PR now and get a SSR error likely coming from it.

**Comment by flornkm** [comment]
The error seems to be that the heading for stack can't be resolved, I tried fixing it but then all other messages got deleted. I will look into it again tomorrow.

**Comment by samuelstroschein** [comment]
@flornkm what's the status?

**Comment by flornkm** [comment]
Closing this as someone already had changed some of the messages added here in our main branch and the merge conflicts are not resolvable in a little amount of time given the format of `messages.json`. The UI was changed too.

Tried to resolve it in an extra branch too but it seems like keys have changed since then, and the German language gets deleted when merging:
Screenshot 2023-11-23 at 1 16 07 PM


Not the fault of the contributor, but we need a better / faster workflow for merging language files. Resolving `messages.json` files that are adjusted for machine readability is a pain and leads to us having to close PRs.

cc @felixhaeberle

**Pull request closed without merging**
