### PR TITLE
improve tests for create and migrate

### PR DESCRIPTION
**Pull request by janfjohannes**

### CODE REVIEW

**Comment by janfjohannes** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by samuelstroschein** [comment]
@janfjohannes outdated?

**Comment by janfjohannes** [comment]
@samuelstroschein  yes but i might have something to push, will go through @felixhaeberle  s pr from yesterday and if some unfinished tests are all obsolete. will close this  or push them here

**Comment by felixhaeberle** [comment]
feel free to add / improve tests tests & clean up

**Comment by felixhaeberle** [comment]
@janfjohannes outdated?

**Pull request closed without merging**
