### PR TITLE
fix lint reactivity in ide extension

### PR DESCRIPTION
**Pull request by felixhaeberle**

### CODE REVIEW

**Comment by felixhaeberle** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by samuelstroschein** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by felixhaeberle** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by felixhaeberle** [comment]
@NiklasBuchfink @floriandwt can you sign the CLA (in this PR)?

**Comment by floriandwt** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by felixhaeberle** [comment]
closing because work continues in other PR's.

**Pull request closed without merging**
