### PR TITLE
chore: refactor event emitters

### PR DESCRIPTION
**Pull request by openscript**

### CODE REVIEW

**Review by felixhaeberle — APPROVED** [review]
+1 lgtm

**Comment by felixhaeberle** [comment]
@openscript We don't do patches anymore. We switched to ComVer instead of SemVer. See reasoning behind https://inlang.com/documentation/comver 

cc @samuelstroschein I see us communicating this a lot in the future 😄

**Comment by samuelstroschein** [comment]
Both work. I wouldn't be too strict about SemVer vs ComVer.

**Comment by felixhaeberle** [comment]
This is confusing 😄

**Comment by samuelstroschein** [comment]
@felixhaeberle the alternative is to open a PR to changesets which enables a `noPatchVersions` config and doesn't prompt the developer if something is a patch

**Comment by openscript** [comment]
> @felixhaeberle the alternative is to open a PR to changesets which enables a `noPatchVersions` config and doesn't prompt the developer if something is a patch

We probably both have been lurking around in the changesets config options, to see if this is possible to configure already.

**Comment by openscript** [comment]
> @felixhaeberle the alternative is to open a PR to changesets which enables a `noPatchVersions` config and doesn't prompt the developer if something is a patch

The api is probably cleaner to have a `versioningScheme` option or so..

**Comment by felixhaeberle** [comment]
@samuelstroschein created an issue over at changeset https://github.com/changesets/changesets/issues/1241

**Pull request merged**
