### PR TITLE
Add italian translations

### PR DESCRIPTION
**Pull request by albbus-stack**
I added all the translation messages for the `it` (italian) language.

This was done entirely through the inlang editor, you guys rock 🤘

### CODE REVIEW

**Comment by albbus-stack** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by albbus-stack** [comment]
recheck

**Comment by samuelstroschein** [comment]
Grazie!

**Comment by felixhaeberle** [comment]
cc @flornkm Do you want to review this & resolve the merge conflict?

**Comment by flornkm** [comment]
Hey @albbus-stack – thanks for your contribution. Git messed up something, but we've merged your PR in #1631 and you're obviously counted as a contributor 😉

Had to resolve the conflicts separately. Therefore closing this PR without merging.

**Pull request closed without merging**
