### PR TITLE
Implement SEO for Fink

### PR DESCRIPTION
**Pull request by flornkm**
This PR will introduce SEO for Fink. Main benefits:
- Backlinks are already there for inlang projects 
- The more Fink scales, the more visibility 
- Reactive Page Titles based on page mounting

### CODE REVIEW

**Comment by flornkm** [comment]
@NiklasBuchfink I think we should merge this ultimately before Fink moves to `fink.inlang.com` cause I have made some other SEO additions.

**Comment by NiklasBuchfink** [comment]
@NilsJacobsen This could be an opportunity to optimize SEO for CAT/TMS tools.

**Comment by NilsJacobsen** [comment]
Sure but let's merge first

**Review by NiklasBuchfink — APPROVED** [review]
The i18n keywords will be changed to CAT/TMS in the future, but let's merge this first. I hope that this will have a huge impact on growth.

**Comment by samuelstroschein** [comment]
Merge?

**Pull request merged**
