### PR TITLE
introduce better inlang search

### PR DESCRIPTION
**Pull request by floriandwt**
### This PR introduces a better search for inlang powered by Algoria + other improvements for the overall UX

**Changes:**
- New rpc function using Angolia to fetch search results
- Categories listed below `/c/` are now dynamic for simplicity reasons
- Items are now listed below `/m/´
- Guides are introduced and listed below `/g/`
- Full search listed on `/search`
- SearchBar is reactive based on URL query
- SearchBar sets URL query accordingly
- SearchBar is smart and knows when visiting a category
- SearchBar is adding `?q=SEARCHWORD` so links are also sharable 
- `components` folder is now `interface` as it includes more than just components.
- Unnecessary components got deleted to enhance DX when contributing
- Documentation index page quick start link adjusted
- Mobile menus adjusted (submenu in marketplace + sticky submenu in docs) 
- Marketplace registry is adding uniqueIDs to each item which is a big benefit if a e.g. someone changes the name of an item
- Marketplace registry automatically checks if uniqueIDs are really unique
- Marketplace registry is uploading the registry to Algolia to sync everything
- Merketplace registry allows local node file reading
- Manifest of paraglide changed (name)

### CODE REVIEW

**Comment by NilsJacobsen** [comment]
I added stack again on landing page :)

**Comment by floriandwt** [comment]
> I added stack again on landing page :)

Ah nice thanks @NilsJacobsen <3

**Review by NiklasBuchfink — APPROVED** [review]
Top job 👍

**Comment by floriandwt** [comment]
A changeset results in the whole CI script not working again… should we merge tomorrow morning instead? @NilsJacobsen @NiklasBuchfink 
After merging I can support Nils with the docfooding and the therefore changes search routes.

**Review by NilsJacobsen — APPROVED** [review]
Nice let's merge this tomorrow morning so we can fix stuff in case something went wrong.👍

**Comment by NilsJacobsen** [comment]
Now it's green let's merge this. @floriandwt

**Pull request merged**
