### PR TITLE
feat: Check for CLI package updates

### LINKED ISSUE #1591: notify to update CLI to latest major version / auto-update to latest minor
## Current Behavior

At present, users may not be aware of the availability of new releases, and manual updates are required. This can lead to users running outdated versions with known bugs.

## Opportunity

To enhance user experience and mitigate potential issues, it would be beneficial to implement a notification mechanism urging users to update to the latest version. Additionally, providing an option for auto-updating to the latest minor version can streamline the process and ensure users are on the most stable release.

## Proposal

- Users should receive notifications within the CLI interface when a new version is available. 
- Additionally, users should have the option to auto-update to the latest minor version directly from the CLI prompt.

### Implementation

only a rough sketch, misses a few parts:
- run on "preHook"
- have minimal surface API `latestVersion, currentVersion, update()`
- have minor update happen in background, notify on major

```ts
  .hook("preAction", (command) => {
   //...

    // Check for the latest version and notify if there's a major version update
    const latestVersion = getLatestVersion();
    const currentVersion = getCurrentVersion();

    if (isMajorVersionUpdate(currentVersion, latestVersion)) {
      notify(`A major update (${latestVersion}) is available. Please consider updating.`);
      // Optionally, prompt the user to update
      prompt("Do you want to update to the latest version?");
    } else {
      // Check for the latest minor version and update automatically in the background
      updateToLatestMinor();
    }
  });
  
// --------------- //  
// UPDATE UTILS
// --------------- //

// Dummy function to check if there's a major version update
export function isMajorVersionUpdate(currentVersion: string, latestVersion: string): boolean {
  return semver.major(currentVersion) !== semver.major(latestVersion);
}

// Function to get the current version by executing "npx @inlang/cli -v"
export function getCurrentVersion(): string | null {
  try {
    const output = execSync('npx @inlang/cli -v', { encoding: 'utf-8' });
    // Extract the version from the output (assuming it's in the format "vX.Y.Z")
    const match = output.match(/v(\d+\.\d+\.\d+)/);
    return match ? match[1] : null;
  } catch (error) {
    console.error('Error getting current version:', error.message);
    return null;
  }
}

// Function to update to the latest minor version in the background
export function updateToLatestMinor(): void {
  try {
    // Execute the update command in the background
    execSync('npx @inlang/cli@latest', { stdio: 'ignore' });
  } catch (error) {
    console.error('Error updating to the latest minor version:', error.message);
  }
}
```

### PR DESCRIPTION
**Pull request by rishi-raj-jain**
fix #1591
/claim #1591

### CODE REVIEW

**Comment by rishi-raj-jain** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by rishi-raj-jain** [comment]
@felixhaeberle

How is this looking? Anywhere I can make improvements? Happy to contribute the best thing that makes sense for you.

**Comment by felixhaeberle** [comment]
@rishi-raj-jain Will review it tomorrow 👍

**Comment by rishi-raj-jain** [comment]
@felixhaeberle 

I've left a reply in Discord. Thanks!

**Comment by felixhaeberle** [comment]
@rishi-raj-jain 

Can you add a "minor" changeset for the cli describing your change with "npx changeset" executed in the root of the repo? This will create a new minor release once merged.

**Comment by rishi-raj-jain** [comment]
@felixhaeberle 

Done

**Comment by felixhaeberle** [comment]
@rishi-raj-jain Do you need any additonal input?

**Comment by rishi-raj-jain** [comment]
Hey @felixhaeberle.

I've just pushed the tests.

**Comment by rishi-raj-jain** [comment]
Tested for the cases:

- it gets the correct current version of if globally installed cli package
- if the user chooses to update if a major update is found
- if the user chooses to NOT update if a major update is found
- if the system had a minor version and it updates correctly in the background

**Comment by felixhaeberle** [comment]
Enabled CI/CD. let's see if everything runs through smoothly.

**Comment by rishi-raj-jain** [comment]
Lint seems to be failing lol

**Comment by rishi-raj-jain** [comment]
How do I run the lint locally? I tested my tests with npm run test after changing to cli directory.

**Comment by rishi-raj-jain** [comment]
@felixhaeberle 

Running linter fix

**Comment by rishi-raj-jain** [comment]
@felixhaeberle 

Looks like editor and website project fail the lint which is outside of this PR purview.

Screenshot 2023-11-16 at 3 35 01 PM


Fixed the lint issue for cli.

**Comment by rishi-raj-jain** [comment]
> Enabled CI/CD. let's see if everything runs through smoothly.

Can you run the workflow again? It requires approval on your end.
Screenshot 2023-11-16 at 3 37 54 PM

**Comment by rishi-raj-jain** [comment]
Below are the tests that are failing (purview outside of this PR), the CLI tests passed like a charm.

Screenshot 2023-11-16 at 3 47 57 PM

**Comment by felixhaeberle** [comment]
@rishi-raj-jain Merged as the failing tests have nothing to do with the CLI

**Comment by felixhaeberle** [comment]
@rishi-raj-jain The failing CI was related to the CLI & we had to revert the PR, unfortunately, the testing strategy of globally installing the CLI on the CI and the non-silent prompt in the CLI broke multiple setups. We will iterate upon your changes and find another solution with no prompting & simply logging new version if available.

**Pull request merged**
